### ISSUE TITLE
I had to add one line before this to get the install to work

### ISSUE THREAD

**Issue by isaackod** [cnstlungu/portable-data-stack-dagster#2]
https://github.com/cnstlungu/portable-data-stack-dagster/blame/6e743e7a1f28c8c5186606d7afcaa1f7a77b771d/generator/Dockerfile#L14

RUN apt-get update \
    && apt-get -y install libpq-dev gcc

**Comment by cnstlungu** [comment]
Hello @isaackod ! Thanks for reaching out.

Can you please share what error were you seeing that you fixed with the above?

I've just tried starting up the suite and it works fine (well, I found another, seemingly unrelated issue and fixed it).


![image](https://github.com/cnstlungu/portable-data-stack-dagster/assets/10930578/819d4602-3c03-4311-8f8c-9d30f0fd9805)

![image](https://github.com/cnstlungu/portable-data-stack-dagster/assets/10930578/75431eeb-3e39-4102-b91e-5e7104cfd9e4)

**Comment by cnstlungu** [comment]
Closing this issue.
